import { chromium } from 'playwright';
const BIN='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const b=await chromium.launch({headless:true,executablePath:BIN,args:['--no-sandbox']});
const p=await b.newPage();
p.on('pageerror',e=>console.log('  [pageerror]',e.message.slice(0,180)));
await p.goto('http://localhost:3041/login',{waitUntil:'domcontentloaded'});
await p.fill('#password','pw'); await p.click('button[type=submit]');
await p.waitForTimeout(1500);
await p.goto('http://localhost:3041/episode/e1',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(1500);
console.log('  Knopf:', await p.textContent('#saveBtn'));
console.log('  Hinweis anfangs:', (await p.textContent('#saveHint')).trim());
await p.fill('#epDesc','Neuer Text');
await p.waitForTimeout(300);
console.log('  Nach Tippen:     ', (await p.textContent('#saveHint')).trim());
await p.click('#saveBtn'); await p.waitForTimeout(1200);
console.log('  Nach Speichern:  ', (await p.textContent('#saveHint')).trim());
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(1500);
console.log('  Nach Neuladen:   ', JSON.stringify(await p.inputValue('#epDesc')));
await b.close();
